
name: "reader360Server"
mode: "dev"
port: 8088
version: "1.0.0"
start_time: "2023-03-20"
machine_id: 1

common:
  jwt_overtime: 60
log:
  level: "debug"
  filename: "gin_cli.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "Admin123456"
  dbname: "reader360"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100